stages:
  - build
  - deploy

build:
  stage: build
  image: registry.ekuaibao.com/ci/ci-nodejs:10.0
  script:
    - npm --registry https://repo.ekuaibao.com/repository/npm-group/ install
    - npm run build
    - npm run publish2npm
  only:
    - /^v?\d+(\.\d+)+[\.\-_\w]*/
  tags:
    - docker
